### ISSUE TITLE
Odd formatting of checkbox

### ISSUE THREAD

**Issue by ghost** [BurningTreeC/tiddlywiki-muuri-kanban#1]
Hello, when I add checkboxes to a tiddler the checkbox appears to the right rather than on the left found here:

https://tiddlywiki.com/#CheckboxWidget

Here is the markup I'm using.
<$checkbox>Subtask1</$checkbox>
<$checkbox>Subtask2</$checkbox>
<$checkbox>Subtask3</$checkbox>

I was curious if this could be corrected. 

Thank you for the project! I think it is going to suit my need well.

**Comment by BurningTreeC** [comment]
Hi, I've found the culprit for this. It's in `$:/plugins/BTC/Muuri-Kanban/css`

The lines
```
.tc-board-item-content input {
	width: 100%;
	border: 1px solid <<colour muted-foreground>>;
	border-radius: 2px;
	margin-bottom: 2px;
}
```
need to be changed to

```
.tc-board-item-content input:not(input[type="checkbox"]) {
	width: 100%;
	border: 1px solid <<colour muted-foreground>>;
	border-radius: 2px;
	margin-bottom: 2px;
}
```
