### ISSUE TITLE
Clicking the 'new item' button on columns does not add the new tiddler to the list field of the column tiddler

### ISSUE THREAD

**Issue by AshRubigo** [BurningTreeC/tiddlywiki-muuri-kanban#3]
Note: Columns do not even have a list field at all.
Note: Even if a list field is manually added to the column tiddler, the exected behaviour does not resume.
Note: Tiddlers can be manually added to the list field of column tiddlers and they will show up on the kanban board.

**Environment:**
Version: Main github branch.
Browser: Firefox 90.0.2.
TiddlyWiki: 5.1.23.

**Steps to reproduce:**

1. Create a kanban board tiddler.
2. Create a column on that board.
1. Click the 'new item' button on the column.

**Expected result:**

The new card tiddler would show up in the column on the kanban board.

**Comment by AshRubigo** [comment]
Issue not present using TiddlyWiki 5.2.0-prerelease.

**Comment by BurningTreeC** [comment]
Closing this. I've added a notification about the tiddlywiki version compatibility of the plugin
