### ISSUE TITLE
kanban-history field entries do not have a date

### ISSUE THREAD

**Issue by AshRubigo** [BurningTreeC/tiddlywiki-muuri-kanban#5]
**Environment:**
Version: Main github branch.
Browser: Firefox 90.0.2.
TiddlyWiki: 5.1.23.

**Steps to reproduce:**

1. Create a kanban board tiddler with some columns.
2. Create a tiddler to be used as a card tiddler.
1. Manually add the card tiddler to the list field of a column tiddler.
2. Move the card to different columns.
3. Outside of the kanban board interface, open the card tiddler and see the kanban-history field.

**Expected result:**

kanban-history field entries would have a date.

**Comment by AshRubigo** [comment]
Issue not present using TiddlyWiki 5.2.0-prerelease.

**Comment by BurningTreeC** [comment]
Closing this. I've added a notification about the tiddlywiki version compatibility of the plugin
