### ISSUE TITLE
No matter how many moves are made between columns, there are never more than 2 items in a card tiddler's kanban-history field

### ISSUE THREAD

**Issue by AshRubigo** [BurningTreeC/tiddlywiki-muuri-kanban#6]
**Environment:**
Version: Main github branch.
Browser: Firefox 90.0.2.
TiddlyWiki: 5.1.23.

**Steps to reproduce:**

1. Create a kanban board tiddler with some columns.
2. Create a tiddler.
1. Manually add the tiddler to the list field of the column tiddler.
2. Click the 'kanban history' button on the card to see the kanban-history changes.
2. Move the card between columns several times.
3. See how the history gets overwritten each time.

**Expected result:**

Each move would get appended to the list.

**Comment by AshRubigo** [comment]
Issue not present using TiddlyWiki 5.2.0-prerelease.

**Comment by BurningTreeC** [comment]
Closing this. I've added a notification about the tiddlywiki version compatibility of the plugin
