### ISSUE TITLE
No horizontal scroll bar?

### ISSUE THREAD

**Issue by dillfrescott** [BurningTreeC/tiddlywiki-muuri-kanban#8]
It would be great to have a horizontal scroll bar to go through the columns of the kanban board. Because right now, if you have many columns, they eventually get squished together until it becomes unusable. Unless there is actually a way to remedy this, please let me know!

**Comment by BurningTreeC** [comment]
Hello @DillFrescott , there is a way to do so. Go to the ControlPanel, open the `Appearance` Tab, then the `Muuri-Kanban` Tab and check the checkbox for `enable horizontal scrolling for Kanbans`

**Comment by jreoka** [comment]
@BurningTreeC Awesome! Just what I wanted! Thank you!!!!!
